### ISSUE TITLE
How to hide ControlCenter?

### ISSUE THREAD

**Issue by 16alexanders** [BenEmdon/CenteredCollectionView#17]
Hi, I adapted code from the Example project and everything is working perfectly but I'd like to disable the control center. 

I've tried setting the isHidden property of the ControlCenterView to true but that broke functionality.
I tried setting the various switches and labels contained in the ControlCenterView but that also broke functionality.

What's the simplest way to remove them from the project while keeping the CenteredCollectionView in horizontal format? 

This is what happens when I try to hide the ControlCenterView...
![screenshotcollectionview](https://cloud.githubusercontent.com/assets/6835342/26074039/530b8210-3965-11e7-878b-22219a5579cd.png)

**Comment by BenEmdon** [comment]
Hey @16alexanders,

So whats happening here is that your CollectionView has enough vertical space to show two cells vertically. The fix for this would be to make your CollectionView shorter (and not take up the whole screen) or to make your Collection cells taller.

Hope this helps 👋  **Reopen the issue if you still need help**
