### ISSUE TITLE
Support self-sizing cell

### ISSUE THREAD

**Issue by Koosj** [BenEmdon/CenteredCollectionView#18]
Hello:)
First, thank you for you made this library. It's very helpful for me.
I have a question.
Do you support self-sizing cell?

**Comment by BenEmdon** [comment]
Hey, 

Glad this repo has helped! 

Sadly support for self sizing cells isn't really robust. You can give it a try by using a `UICollectionViewDelegateFlowLayout`. The `contentInset` calculation relies on the current sizes of the cells at load time, which is likely before your delegate is called, so you would have to invalidate the `collectionViews` `flowLayout` to ensure that the inset calculation is correct.

There's isn't any plans to support this functionality because it could reduce the robustness of the project. Closing this for now, just reopen if you have any more questions.

**Comment by Koosj** [comment]
thank your for answer
