### ISSUE TITLE
Objective C support

### ISSUE THREAD

**Issue by farazhaider88** [BenEmdon/CenteredCollectionView#38]
dear,

how can i use this in objective c project. please help.

**Comment by BenEmdon** [comment]
@farazhaider88 I think the best place to get an answer to this question is to look at Apples documentation. https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c

I am not sure this package will work out of the box with Objective-C (as I have not tried). If you find a way to make this work please report/contribute back!

**Comment by duraki** [comment]
I don't want to open new issue but I've tried this extension with Objective-C and it works very well. The only problem is we can't observe the `currentCenteredPage`.

```
NSInteger *currentIndex = self.centeredCollectionViewFlowLayout.currentCenteredPage;
```
Throws error `Property 'currentCenteredPage' not found on object of type 'CenteredCollectionViewFlowLayout *'`. I'm guessing it's because of `Int?` but I'm not proficient with Swift enough. Any input is highly appreciated.

Thanks!

**Comment by duraki** [comment]
Taken from Apple documentation:

`Optional values of non-Objective-C types aren't bridged into Objective-C.`

@BenEmdon

**Comment by duraki** [comment]
This is how I did it (hotfix, not sure how smart it is):

```
    /// Calculates the current centered page.
    @objc public var currentCenteredPage: Int {
        guard let collectionView = collectionView else { return -1 }
        let currentCenteredPoint = CGPoint(x: collectionView.contentOffset.x + collectionView.bounds.width/2, y: collectionView.contentOffset.y + collectionView.bounds.height/2)
        
        return collectionView.indexPathForItem(at: currentCenteredPoint)?.row ?? -1
    }
```

Returns `-1` if no cell is at centered point.

**Comment by BenEmdon** [comment]
@duraki this seems like a reasonable change, but it would break the API. If you would like an API to observe `currentCenteredPage` we could instead create a new API. If you submit a PR, I will definitely review it 😉

**Comment by duraki** [comment]
Well, I can try. What do you suggest as a starting point regarding the Swifts version of `currentCenteredPage`?

**Comment by BenEmdon** [comment]
Instead of modifying the swift implementation of `currentCenteredPage`, you could write a new calculated variable and implement it exactly like so https://github.com/BenEmdon/CenteredCollectionView/issues/38#issuecomment-601413194.

Deciding the name of such a variable is the hard part 😅 Here are some name ideas:
- `currentCenteredPageOBJC`
- `currentCenteredIndex`

**Comment by BenEmdon** [comment]
@duraki still interested in doing this?

**Comment by duraki** [comment]
Sure, although a bit busy right now with the case of pandemic. If anyone is able to tackle it down I'm more then available to help.

**Comment by BenEmdon** [comment]
@duraki Take care of yourself 💖I totally feel you and I have also had less bandwidth during this time. 

I'll add the `help wanted` label in case anyone else wants to pick this up 👋

**Comment by wassup-** [comment]
To access the current centered page from ObjC, this is probably all you need:
```swift
@objc var currentCenteredPageNumber: NSNumber? {
    currentCenteredPage as NSNumber?
}
```
