### ISSUE TITLE
how to centered collectionview with loadmore 

### ISSUE THREAD

**Issue by DGP13** [BenEmdon/CenteredCollectionView#45]
How to center collection view with load more pull to refresh all data.

**Comment by BenEmdon** [comment]
Hey @DGP13, 
Your question pertains to `UICollectionView's in general and not the `UICollectionViewFLowLayout` subclass in this package.
 
Your question would be best answered by a looking through Apple's `UICollectionView` documentation. Also this might be a decent resource to look at: https://cocoacasts.com/how-to-add-pull-to-refresh-to-a-table-view-or-collection-view

I am going to close this since your question is off-topic.
