### ISSUE TITLE
Issue with more than 4 cells- actions affect every fourth cell.

### ISSUE THREAD

**Issue by grajan22** [BenEmdon/CenteredCollectionView#52]
Hello,
I'm currently running the example code, except with a twist- I added a button that when clicked makes it unclickable in the future. Now, here's the problem: whenever I click on button 1, button 5 is immediately also unclickable. Could this be an issue with my code, or is it directly related to the CenteredCollectionView?
Thank you! This is such a help.

**Comment by BenEmdon** [comment]
This sounds like it’s due to the fact that cells are are reused. To ensure this doesn’t happen you need to reset your cell/items state on each dequeue. For more context about what I’m talking about, read Apples docs here https://developer.apple.com/documentation/uikit/uicollectionview

Since you haven’t provided enough context to debug, I am going to close this issue.
